name: Lint
on: [push, pull_request]
permissions: {contents: read, statuses: write}

jobs:
  l:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: {distribution: temurin, java-version: '17'}
      - run: |
          curl -sSLo gjf.jar https://github.com/google/google-java-format/releases/download/v1.22.0/google-java-format-1.22.0-all-deps.jar
          FILES="$(git ls-files '*.java' || true)"; [ -n "$FILES" ] && java -jar gjf.jar --replace $FILES || true
      - uses: github/super-linter@v6
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_GOOGLE_JAVA_FORMAT: true
